---
all:
  hosts:
    el-instance:
      ansible_host: 62.84.118.7
    kib-instance:
      ansible_host: 217.28.230.44
    app-instance:
      ansible_host: 193.32.218.52
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu
